# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Time Killer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  	
  # Pods for Time Killer
  pod 'Parse'
  pod 'AlamofireImage'	

  target 'Time KillerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Time KillerUITests' do
    # Pods for testing
  end

end
